/*
The database had some classname fields generated by Morphia. They specified a different classname
for the Rank class than what is specified in this project. This broke Morphia as it generated a
warning each time it tried to fetch an entity with a wrong classname. This script was used to remove
those classnames. Two Morphia-enabled applications can't therefore access (read or write) the same
collection or Morphia breaks.
 */

db.games.update( { "appGenreHistories.7001": { $exists: true }}, { $unset: { "appGenreHistories.7001.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreHistories.7017": { $exists: true }}, { $unset: { "appGenreHistories.7017.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreHistories.7012": { $exists: true }}, { $unset: { "appGenreHistories.7012.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreHistories.7003": { $exists: true }}, { $unset: { "appGenreHistories.7003.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreHistories.7014": { $exists: true }}, { $unset: { "appGenreHistories.7014.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreHistories.7009": { $exists: true }}, { $unset: { "appGenreHistories.7009.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreHistories.7015": { $exists: true }}, { $unset: { "appGenreHistories.7015.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreHistories.7002": { $exists: true }}, { $unset: { "appGenreHistories.7002.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreHistories.7005": { $exists: true }}, { $unset: { "appGenreHistories.7005.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreHistories.7016": { $exists: true }}, { $unset: { "appGenreHistories.7016.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreHistories.7011": { $exists: true }}, { $unset: { "appGenreHistories.7011.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreHistories.7006": { $exists: true }}, { $unset: { "appGenreHistories.7006.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreHistories.7013": { $exists: true }}, { $unset: { "appGenreHistories.7013.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreHistories.7019": { $exists: true }}, { $unset: { "appGenreHistories.7019.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreHistories.7004": { $exists: true }}, { $unset: { "appGenreHistories.7004.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreHistories.7018": { $exists: true }}, { $unset: { "appGenreHistories.7018.$[].className": "" } }, { multi: true});

db.games.update( { "appGenreDhistories.7001": { $exists: true }}, { $unset: { "appGenreDhistories.7001.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreDhistories.7017": { $exists: true }}, { $unset: { "appGenreDhistories.7017.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreDhistories.7012": { $exists: true }}, { $unset: { "appGenreDhistories.7012.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreDhistories.7003": { $exists: true }}, { $unset: { "appGenreDhistories.7003.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreDhistories.7014": { $exists: true }}, { $unset: { "appGenreDhistories.7014.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreDhistories.7009": { $exists: true }}, { $unset: { "appGenreDhistories.7009.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreDhistories.7015": { $exists: true }}, { $unset: { "appGenreDhistories.7015.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreDhistories.7002": { $exists: true }}, { $unset: { "appGenreDhistories.7002.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreDhistories.7005": { $exists: true }}, { $unset: { "appGenreDhistories.7005.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreDhistories.7016": { $exists: true }}, { $unset: { "appGenreDhistories.7016.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreDhistories.7011": { $exists: true }}, { $unset: { "appGenreDhistories.7011.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreDhistories.7006": { $exists: true }}, { $unset: { "appGenreDhistories.7006.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreDhistories.7013": { $exists: true }}, { $unset: { "appGenreDhistories.7013.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreDhistories.7019": { $exists: true }}, { $unset: { "appGenreDhistories.7019.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreDhistories.7004": { $exists: true }}, { $unset: { "appGenreDhistories.7004.$[].className": "" } }, { multi: true});
db.games.update( { "appGenreDhistories.7018": { $exists: true }}, { $unset: { "appGenreDhistories.7018.$[].className": "" } }, { multi: true});